### ISSUE TITLE
Do not starts second time.

### ISSUE THREAD

**Issue by anddorua** [marius-nyxpoint/vagrant-php5.2#2]
It does not start again after halt. (Ubuntu 15.10, VirtualBox 5.1). Helps inserting config line to Vagrantfile
`config.ssh.insert_key = false`
before first up. But this seems not good idea concerning security.

**Comment by marius-cojocariu** [comment]
This is an expected behaviour, because:
1) vagrant keeps renewing ssh keys that he uses to connect to any virtual machine
2) the box that is used to create the config is very old, it's a precise ubuntu, which is no longer supported

I'm not worried about security concerns here, heck, we are using php 5.2 which has not received security updates for over 5 years.

I'm not using this anymore, but if you can provide a PR with the changes, that would be great :smile:.
